=== Johantandukar/test/Development/catalog_18030039.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="shop">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Address" type="xs:string" />
              <xs:element name="Telephone" type="xs:string" />
              <xs:element name="URL" type="xs:anyURI"/>
              <xs:element name="logo" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="cartypes">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Hatchbacks">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Hatchback" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" />
                          <xs:element name="bandname" type="xs:string" />
                          <xs:element name="module" type="xs:string" />
                          <xs:element name="item_number" type="xs:string" />
                          <xs:element name="description" type="xs:string" />
                          <xs:element name="quantity" type="xs:integer" />
                          <xs:element name="price_rs">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:int">
                                  <xs:attribute name="rscurrency" type="xs:string"  use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="price_dollar" type="xs:string" />
                          <xs:element name="price_pound" type="xs:string" />
                          <xs:element name="delivery" type="xs:string" />
                          <xs:element name="information">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="manufactureryear" type="xs:short" />
                                <xs:element name="fueltype" type="xs:string" />
                                <xs:element name="color" type="xs:string" />
                                <xs:element name="mileage" type="xs:string" />
                                <xs:element name="enginecc" type="xs:string" />
                                <xs:element name="wheelbase" type="xs:string" />
                                <xs:element name="dimension">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="unit" type="xs:string"  use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Sedans">
                <xs:complexType>
                  <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="sedan">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" />
                          <xs:element name="bandname" type="xs:string" />
                          <xs:element name="module" type="xs:string" />
                          <xs:element name="item_number" type="xs:string" />
                          <xs:element name="description" type="xs:string" />
                          <xs:element name="quantity" type="xs:integer" />
                          <xs:element name="price_rs">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:float">
                                  <xs:attribute name="rscurrency" type="xs:string"  use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="price_pound" type="xs:string" />
                          <xs:element type="xs:string" name="delivery"/>
                          <xs:element name="information">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="manufactureryear" type="xs:short" />
                                <xs:element name="fueltype" type="xs:string" />
                                <xs:element name="color" type="xs:string" />
                                <xs:element name="mileage" type="xs:string" />
                                <xs:element name="enginecc" type="xs:string" />
                                <xs:element name="wheelbase" type="xs:string" />
                                <xs:element name="dimension">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="unit" type="xs:string"  use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:choice>
                </xs:complexType>
              </xs:element>
              <xs:element name="Suvs">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="suv" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" />
                          <xs:element name="bandname" type="xs:string" />
                          <xs:element name="module" type="xs:string" />
                          <xs:element name="item_number" type="xs:string" />
                          <xs:element name="description" type="xs:string" />
                          <xs:element name="quantity" type="xs:integer" />
                          <xs:element name="price_rs">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:int">
                                  <xs:attribute type="xs:string" name="rscurrency" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="price_dollar" type="xs:string"  minOccurs="0" maxOccurs="unbounded"/>
                          <xs:element name="price_pound" type="xs:string" />
                          <xs:element name="delivery" type="xs:string"  minOccurs="0"/>
                          <xs:element name="information">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="manufactureryear" type="xs:integer" />
                                <xs:element name="fueltype" type="xs:string" />
                                <xs:element name="batterylife" type="xs:string"  minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element name="color" type="xs:string" />
                                <xs:element name="mileage" type="xs:string"  minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element name="enginecc" type="xs:string"  minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element name="wheelbase" type="xs:string"  minOccurs="0" maxOccurs="unbounded"/>
                                <xs:element name="dimension">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:string" name="unit" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Coupes">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Coupe" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" />
                          <xs:element name="bandname" type="xs:string" />
                          <xs:element name="module" type="xs:string" />
                          <xs:element name="item_number" type="xs:short" />
                          <xs:element name="description" type="xs:string" />
                          <xs:element name="quantity" type="xs:byte" />
                          <xs:element name="price_rs">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:int">
                                  <xs:attribute name="rscurrency" type="xs:string"  use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="price_dollar"/>
                          <xs:element type="xs:string" name="price_pound"/>
                          <xs:element name="information">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="manufactureryear"  type="xs:integer"/>
                                <xs:element name="fueltype" type="xs:string" />
                                <xs:element name="color" type="xs:string" />
                                <xs:element name="mileage" type="xs:string" />
                                <xs:element name="enginecc" type="xs:string" />
                                <xs:element name="wheelbase" type="xs:string" />
                                <xs:element name="dimension">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="unit" type="xs:string" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ref" type="xs:string"  use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Pickups">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="pickup" minOccurs="0" maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" />
                          <xs:element name="bandname" type="xs:string" />
                          <xs:element name="module" type="xs:string"/>
                          <xs:element name="item_number" type="xs:string" />
                          <xs:element name="description" type="xs:string" />
                          <xs:element name="quantity" type="xs:integer" />
                          <xs:element name="price_rs">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:int">
                                  <xs:attribute name="rscurrency" type="xs:string"  use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="price_dollar" type="xs:string"  minOccurs="0" maxOccurs="unbounded"/>
                          <xs:element name="price_pound" type="xs:string"/>
                          <xs:element name="delivery" type="xs:string"  minOccurs="0" maxOccurs="unbounded"/>
                          <xs:element name="information">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="manufactureryear" type="xs:integer" />
                                <xs:element name="fueltype" type="xs:string" />
                                <xs:element name="color" type="xs:string" />
                                <xs:element name="mileage" type="xs:string" />
                                <xs:element name="enginecc" type="xs:string" />
                                <xs:element name="dimension">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="unit" type="xs:string" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Vans">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Van">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" />
                          <xs:element name="bandname" type="xs:string" />
                          <xs:element name="module" type="xs:string" />
                          <xs:element name="item_number" type="xs:short" />
                          <xs:element name="description" type="xs:string" />
                          <xs:element name="quantity" type="xs:integer" />
                          <xs:element name="price_rs">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:int">
                                  <xs:attribute name="rscurrency" type="xs:string" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="price_pound" type="xs:string" />
                          <xs:element name="information">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="manufactureryear" type="xs:integer" />
                                <xs:element name="fueltype" type="xs:string" />
                                <xs:element name="color" type="xs:string" />
                                <xs:element name="mileage" type="xs:string"/>
                                <xs:element name="enginecc" type="xs:string" />
                                <xs:element name="dimension">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:string" name="unit"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Johantandukar/test/Development/catalog_18030039.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Author: Johan Tandukar 
	Group: C15
	Londonmet ID: 18030039
-->
<?xml-stylesheet type = "text/css" href="catalog_18030039.css"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 		xsi:noNamespaceSchemaLocation="catalog_18030039.xsd">

	<shop>
		<Name>Kathmandu Automobile Center</Name>
		<Address>Tangal Marg, Kathmandu</Address>
		<Telephone>+977-014420555</Telephone>
		<URL>www.kathmanduautomobiles.com.np</URL>
		<logo></logo>
	</shop>

	<cartypes>

		<Hatchbacks>
			
			<Hatchback>
				<name>Toyota Corolla LX</name>
				<bandname> Toyota </bandname>
				<module>Corolla LX</module>
				<item_number>11001</item_number>
				<description><![CDATA[ Toyota Corolla is a line of subcompact and compact cars manufactured by Toyota, Japan. It was introduced in 1966, the Corolla was the best-selling car worldwide by 1974 and has been one of the best-selling cars in the world since then. In 1997, the Corolla became the best selling nameplate in the world, surpassing the Volkswagen Beetle. Toyota reached the milestone of 44 million Corollas sold over twelve generations in 2016. The series has undergone several major redesigns.]]></description>
				<quantity>1</quantity>
				<price_rs rscurrency="Rs">1825000</price_rs>
				<price_dollar>$ 15046.44</price_dollar>
				<price_pound>&#163; 12088.41</price_pound>
				<delivery>Free Delivery</delivery>

				<information>
					<manufactureryear>2011</manufactureryear>
					<fueltype>Petrol</fueltype>
					<color>Golden</color>
					<mileage>21.43 kmpl</mileage>
					<enginecc>1794 CC</enginecc>
					<wheelbase>2700 millimeter</wheelbase>
					<dimension unit="mm">4651L x 1775W x 1455H </dimension>
				</information>
			</Hatchback>


			<Hatchback>
				<name>Suzuki Wagon R Vxi</name>
				<bandname>Suzuki</bandname>
				<module>Wagon R Vxi</module>
				<item_number>12001</item_number>
				<description><![CDATA[ The Suzuki Wagon R is a kei car manufactured and marketed by Suzuki since 1993. The R in the name stands for Revolution and Relaxation . The Wagon R uses a "tall wagon" configuration to maximize cabin space within kei car dimensional restrictions. Wagon R is well proven car and huge presence of the same on roads indicate the same. A fine combination of decent power and mileage, good interiors are the advantages. However with advant of too many new models with updated styling and technical features, there is set back in sales of Wagon R as new car.]]></description>
				<quantity>3</quantity>
				<price_rs rscurrency="Rs">1489000</price_rs>
				<price_dollar>$ 12176.58</price_dollar>
				<price_pound>&#163;11196.86</price_pound>
				<delivery>Free Delivery</delivery>

				<information>
					<manufactureryear>2019</manufactureryear>
					<fueltype>Petrol</fueltype>
					<color>Matte White</color>
					<mileage>22 Kmpl</mileage>
					<enginecc>1197 CC</enginecc>
					<wheelbase>2400 millimeter</wheelbase>
					<dimension unit="mm">3539L x 2400W x 1670H </dimension>
				</information>

			</Hatchback>

			<Hatchback>
				<name>Facelift Hyundai i20 Magna</name>
				<bandname>Hyundai</bandname>
				<module>i20 Magna</module>
				<item_number>12222</item_number>
				<description><![CDATA[ Hyundai Elite i20 is quite high on style quotient due to the European touch in the exterior designing, which is definitely benefiting the company. It is said, "First impression is the last impression"; the same holds true in case of cars First things first, Hyundai Elite i20 pays no resemblance to the outgoing model of the hatch, at least in the exterior appearance. The Fluidic Sculpture 2.0 design philosophy is quite contemporary, quite similar to the one that Peugeot ( French automaker) cars adorn.]]></description>
				<quantity>2</quantity>
				<price_rs rscurrency="Rs">1895000</price_rs>
				<price_dollar>$ 15500.89</price_dollar>
				<price_pound>&#163;14253.06</price_pound>
				<delivery>Free Delivery</delivery>

				<information>
					<manufactureryear>2013</manufactureryear>
					<fueltype>Petrol</fueltype>
					<color>Grey</color>
					<mileage>42 kmpl</mileage>
					<enginecc>1200</enginecc>
					<wheelbase>2570 millimeter</wheelbase>
					<dimension unit="mm">3985L x 1734W x 1505H </dimension>
				</information>
			</Hatchback>

		</Hatchbacks>

		<Sedans>

			<sedan>
				<name>VERNA</name>
				<bandname>Hyundai</bandname>
				<module>VERNA</module>
				<item_number>15001</item_number>
				<description><![CDATA[The Hyundai Verna is based on Hyundaiâ€™s fluidic design, which makes the Verna the best-looking sedan in this segment. The cascading grille and the sharp design language give the Verna a sporty stance. The Verna is offered with a choice of one diesel and two petrol engine. This helps Hyundai cater to a wider audience who are looking for a car that ticks multiple boxes. The Hyundai Verna offers the best performance in the mid-size segment, be it with diesel or petrol. The choice of 1.6-litre diesel and petrol engines suit enthusiastic drivers as well as those looking for a car to commute in the city or enjoy long highway drives. The Hyundai Verna is well-equipped when it comes to safety as well. While dual airbags with ABS and EBD are standard across variants, the top-spec variant gets 6 airbags, ISOFIX child seat anchors, and more.]]></description>
				<quantity>2</quantity>
				<price_rs rscurrency="Rs">4256000</price_rs>
				<price_pound>&#163; 27822.25</price_pound>
				<delivery>Express Delivery</delivery>
				<information>
					<manufactureryear>2017</manufactureryear>
					<fueltype>Petrol and Diseal</fueltype>
					<color>Black</color>
					<mileage>22 Kmpl</mileage>
					<enginecc>1582 CC</enginecc>
					<wheelbase>2600 millimeter</wheelbase>
					<dimension unit="mm">4440L x 1729W x 1475H </dimension>
				</information>
			</sedan>

			<sedan>
				<name>Hyundai Xcent S</name>
				<bandname>Hyundai</bandname>
				<module>Xcent</module>
				<item_number>15002</item_number>
				<description><![CDATA[Hyundai Xcent S is an exception car one might be looking to buy. It features a very classy exterior, powerful engine and great on performance. It stunning and classy face of Hyundai Xcent S is just fabulous. Hyundai offers a very good mileage on board on both the fuel options diesel and petrol it has a mileage of 19.1 KMPL on petrol and a magnificent mileage of 24 km per liter on diesel which is actually a very good mileage for a sedan like Xcent. Some Acceleration issue is there but that is negligible in front of its mileage and looks.]]></description>
				<quantity>2</quantity>
				<price_rs rscurrency="Rs"> 2896000</price_rs>
				<price_pound>&#163; 18931.68</price_pound>
				<delivery>Express Delivery</delivery>
				<information>
					<manufactureryear>2014</manufactureryear>
					<fueltype>Petrol and Diesel</fueltype>
					<color>Orange</color>
					<mileage>19.1 Kmpl and 24 Kmpl</mileage>
					<enginecc>1197 CC</enginecc>
					<wheelbase>2585 millimeter</wheelbase>
					<dimension unit="mm">3995L x 1660W x 1520H </dimension>
				</information>
			</sedan>

			<sedan>
				<name>Honda Amaze</name>
				<bandname>Honda</bandname>
				<module>Amaze</module>
				<item_number>15003</item_number>
				<description><![CDATA[Honda Amaze was showcased at the 2018 Auto Expo a few months ago, and the Japanese carmaker is gearing up to launch the vehicle in India. The Honda Amaze is an all-new car, built specifically for India on a new platform. Honda is betting big with the Amaze, and the compact sedan is a sure shot hit already. This is the first time Honda is offering a CVT gearbox with the diesel engine. The petrol variant gets a CVT too, with optional paddle shifters. The top-of-the-line VX variant of the new Honda Amaze features a 7-inch infotainment system with Android Auto, Apple CarPlay, and navigation.]]></description>
				<quantity>3</quantity>
				<price_rs rscurrency="Rs">3200000</price_rs>
				<price_pound>&#163; 20063.09</price_pound>
				<delivery>Express Delivery</delivery>
				<information>
					<manufactureryear>2013</manufactureryear>
					<fueltype>Petrol</fueltype>
					<color>White</color>
					<mileage>27.4 Kmpl</mileage>
					<enginecc>1200 CC</enginecc>
					<wheelbase>2470 millimeter</wheelbase>
					<dimension unit="mm">3995L x 1695W x 1501H </dimension>
				</information>
			</sedan>

		</Sedans>

		<Suvs>

			<suv>
				<name>Suv MG ZS EV</name>
				<bandname>MG Motors</bandname>
				<module>MG ZS</module>
				<item_number>14001</item_number>
				<description><![CDATA[The new MG ZS EV is the family-friendly electric car, designed for those who want all the advanatages of a zero emissions vehicle without compromissing on pratically or style. Benefitting from our extensive experience in the manufacture of electric cars and batteries, the manufacture of electric cars and batteries, the ZS EV pairs beautiful design with outstanding technolgy. Powered by a 44.5 kWh, water-cooled lithium-iron battery, you can enjoy a driving range up to 163 miles from a single charge on the WLTP combined cycle.]]> </description>
				<quantity>1</quantity>
				<price_rs rscurrency="Rs">4999000</price_rs>
				<price_pound>&#163; 37591.06</price_pound>
				<delivery>Express Delivery</delivery>

				<information>
					<manufactureryear>2019</manufactureryear>
					<fueltype>Electric</fueltype>
					<batterylife>9 hr </batterylife>
					<color>Red</color>
					<dimension unit="mm">4314L x 1809W x 1644H millimeter</dimension>
				</information>
			</suv>

			<suv>
				<name>Volkswagen Vento Highilne</name>
				<bandname>Volkswagen</bandname>
				<module>Vento</module>
				<item_number>14010</item_number>
